spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          #basedir:
          uri: https://github.com/xiongyongjie/springcloudproject.git
          search-paths:
          default-label:
          username:
          password:
server:
  port: 8888