spring:
  application:
    name: mybatis-app
server:
  port: 9000
#配置h2数据
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/miaoshadb?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: miaosha
    password: miaosha
    #type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      max-idle: 100
      max-total: 500
      max-wait-millis: 1000
  #jpa配置
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#自定义属性
infos:
  info:
     url: http://www.baidu.com/
     data: "this is my data"


#mybatis 配置
mybatis:
  type-aliases-package: com.mybatis.op.model
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000

  mapper-locations:
    - classpath:mappers/*.xml
  type-handlers-package: com.mybatis.op.typehandler

